--set serveroutput on;
DECLARE
  P_NR_MATRICULA VARCHAR2(200);
  P_ID_PESSOA NUMBER;
  P_FG_RETORNO VARCHAR2(200);
  P_DS_RETORNO VARCHAR2(200);
BEGIN
--  P_NR_MATRICULA := 63100041 ; P_ID_PESSOA := 74190 ;  ok
--  P_NR_MATRICULA := 63100204	;  P_ID_PESSOA := 153435; 	erro
--  P_NR_MATRICULA := 63100084 ;    P_ID_PESSOA :=366106; ok

  PK_CAD_CLIENTE_EBS_API.P_INTEGRA_CLIENTE_EBS(
    P_NR_MATRICULA => P_NR_MATRICULA,
    P_ID_PESSOA => P_ID_PESSOA,
    P_FG_RETORNO => P_FG_RETORNO,
    P_DS_RETORNO => P_DS_RETORNO
  );

END;